// One-off data-restore script. Logic mirrors src/lib/utils/pricingEngine.ts
// (parseGamepassCatalogCSV) and src/lib/utils/pricing.ts
// (computeGamepassFieldsFromProfit) exactly, duplicated here as plain JS so
// this can run standalone without the TS path-alias setup. Reads
// scripts/original-catalog.csv and writes scripts/restore-catalog.sql.
//
// Run: node scripts/restore-catalog.mjs

import { readFileSync, writeFileSync } from 'fs'

const ROBUX_RATE = 240

function calculateCost(robuxAmount, rate = ROBUX_RATE) {
  return (robuxAmount / 1000) * rate
}
function calculateStatus(profit) {
  if (profit >= 20) return 'Good'
  if (profit >= 5) return 'Okay'
  return 'Bad'
}

function parseCSVLine(line) {
  const fields = []
  let cur = ''
  let inQuotes = false
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++ } else { inQuotes = false }
      } else {
        cur += ch
      }
    } else if (ch === '"') {
      inQuotes = true
    } else if (ch === ',') {
      fields.push(cur); cur = ''
    } else {
      cur += ch
    }
  }
  fields.push(cur)
  return fields.map(f => f.trim())
}

function toNumberOrNull(s) {
  if (!s || s === '' || s.startsWith('#')) return null
  const n = Number(s)
  return Number.isFinite(n) ? n : null
}

function parseGamepassCatalogCSV(raw, defaultGameName) {
  const lines = raw.split(/\r?\n/)
  const tierRows = []
  const catalogRows = []

  let currentGame = defaultGameName.trim() || 'Uncategorized'
  let inRobuxSell = false
  let taxCovered = true
  let currentRate = ROBUX_RATE

  lines.forEach((line, idx) => {
    const lineNumber = idx + 1
    if (line.trim() === '') return
    if (lineNumber === 1 && line.toLowerCase().startsWith('robux amount,')) return

    const cols = parseCSVLine(line)
    const col1 = cols[0] ?? ''
    if (col1 === '') return

    const amount1 = toNumberOrNull(col1)

    if (amount1 === null) {
      const lower = col1.toLowerCase()
      if (lower === 'robux sell') { inRobuxSell = true; return }
      if (inRobuxSell && lower === 'covered tax') {
        taxCovered = true
        const rate = toNumberOrNull(cols[8])
        if (rate) currentRate = rate
        return
      }
      if (inRobuxSell && lower === 'not covered tax') { taxCovered = false; return }
      inRobuxSell = false
      currentGame = col1
      return
    }

    const col2 = toNumberOrNull(cols[1])
    const col3 = toNumberOrNull(cols[2])
    const col4 = toNumberOrNull(cols[3])
    const col5 = toNumberOrNull(cols[4])
    const col9 = toNumberOrNull(cols[8])
    if (col9 !== null) currentRate = col9

    if (inRobuxSell) {
      const robuxAmount = taxCovered ? (col2 ?? amount1) : amount1
      const price = col3 ?? 0
      const profit = col5 ?? (col4 !== null ? price - col4 : price - calculateCost(robuxAmount, currentRate))
      if (robuxAmount > 0) tierRows.push({ robux_amount: robuxAmount, selling_price: price, profit })
      return
    }

    const your_price = col3 ?? 0
    const profit = col5 !== null ? col5 : your_price - calculateCost(amount1, currentRate)
    const rawName = (cols[7] ?? '').trim()
    const name = rawName !== '' ? rawName : `${amount1.toLocaleString()} Robux`
    catalogRows.push({ gameName: currentGame, name, robux_amount: amount1, your_price, profit })
  })

  return { tierRows, catalogRows }
}

function computeGamepassFieldsFromProfit(robuxAmount, yourPrice, profit) {
  const your_cost = yourPrice - profit
  const robux_rate = robuxAmount > 0 ? (your_cost / robuxAmount) * 1000 : ROBUX_RATE
  const status = calculateStatus(profit)
  return { your_cost, robux_rate, status }
}

function sqlString(s) {
  return `'${String(s).replace(/'/g, "''")}'`
}

// ── Run ──────────────────────────────────────────────────────────────────
const raw = readFileSync(new URL('./original-catalog.csv', import.meta.url), 'utf8')
const { catalogRows } = parseGamepassCatalogCSV(raw, 'Slime rng')

const gameNames = [...new Set(catalogRows.map(r => r.gameName))]

let sql = `-- ─────────────────────────────────────────────────────────────────────────────
-- Restore gamepasses for games affected by the Import Catalog bug, from the
-- original spreadsheet. Generated by scripts/restore-catalog.mjs — parsing
-- logic is identical to src/lib/utils/pricingEngine.ts.
--
-- Wipes ONLY the games listed below, then recreates their gamepasses fresh.
-- Any other game in your catalog is untouched.
-- ─────────────────────────────────────────────────────────────────────────────

DO $$
DECLARE
  v_user_id uuid;
BEGIN
  SELECT user_id INTO v_user_id FROM public.games LIMIT 1;
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'No existing games row found to infer user_id from'; END IF;

`

for (const name of gameNames) {
  sql += `  INSERT INTO public.games (user_id, name)\n`
  sql += `  SELECT v_user_id, ${sqlString(name)}\n`
  sql += `  WHERE NOT EXISTS (SELECT 1 FROM public.games WHERE user_id = v_user_id AND name = ${sqlString(name)});\n\n`
}

sql += `  DELETE FROM public.gamepasses\n`
sql += `  WHERE user_id = v_user_id\n`
sql += `    AND game_id IN (\n`
sql += `      SELECT id FROM public.games WHERE user_id = v_user_id AND name IN (\n`
sql += gameNames.map(n => `        ${sqlString(n)}`).join(',\n')
sql += `\n      )\n    );\n\n`

sql += `  INSERT INTO public.gamepasses (user_id, game_id, name, robux_amount, your_price, your_cost, robux_rate, profit, status, suggested_lower_price, competitor_price, is_active)\n  VALUES\n`

const valueLines = catalogRows.map(row => {
  const fields = computeGamepassFieldsFromProfit(row.robux_amount, row.your_price, row.profit)
  return `    (v_user_id, (SELECT id FROM public.games WHERE user_id = v_user_id AND name = ${sqlString(row.gameName)}), ${sqlString(row.name)}, ${row.robux_amount}, ${row.your_price}, ${fields.your_cost.toFixed(4)}, ${fields.robux_rate.toFixed(4)}, ${row.profit}, ${sqlString(fields.status)}, 0, 0, true)`
})
sql += valueLines.join(',\n')
sql += `;\n\nEND $$;\n`

writeFileSync(new URL('./restore-catalog.sql', import.meta.url), sql, 'utf8')

console.log(`Parsed ${catalogRows.length} gamepass rows across ${gameNames.length} games.`)
console.log('Games:', gameNames.join(', '))
console.log('Wrote scripts/restore-catalog.sql')
