-- Migration 064: Seed first-class Roblox game identity (data only).
--
-- GENERATED by BudgetWise_Store scripts/generate-roblox-identity-seed.mjs.
-- Do not hand-edit; regenerate from the Store sources instead.
--
-- Imports the already-reviewed Roblox identity decisions into
-- public.game_roblox_identity (migration 063) so the database can be proven
-- identical to the trusted Store config before anything reads identity from
-- the database. Nothing consumes these rows yet.
--
-- Sources (BudgetWise_Store):
--   commit                  e81f2515b08740722ad7bef82eb6b9debb9f867c
--   last source change      8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7
--   src/config/roblox-universe-ids.json  blob 6f0471232ba1bea946fda69c708b1c79972b4dd1
--   src/config/roblox-universe-ids.ts    blob 8f3ddb270054f50f734c21756b7797f7624506d2
-- Game names pinned from live public.games on syhzmkbtftyykggtsfxk.supabase.co.
-- Roblox snapshot (root place, name, creator) read from
-- https://games.roblox.com/v1/games at 2026-09-15T12:39:11.496Z during generation.
-- This file makes no network calls.
--
-- Rows (35):
--   verified      26  verification_method = 'legacy_json_import'. The original basis is kept in
--                    verification_evidence.original_method:
--                      gamepass_overlap 24 (Anime Origins: attested only by the legacy source comment)
--                      manual_content_icon_match 1 (Blox Fruits)
--                      owner_confirmed 1 (Karinderya)
--                    verified_at = the commit that introduced the mapping. verified_by stays NULL.
--   not_roblox    3
--   cc1ec858-663c-4ff2-9185-e3d587780b46  ROBUX PLUS
--   bf10c2e9-d9f2-4f86-8c7d-5c94b7354a75  Robux Sell — Covered Tax
--   e5318653-6b19-417c-9f89-1a7baa2331aa  Robux Sell — No Tax
--   needs_review  6  no universe, root place, snapshot, or method is assigned
--   c1855e24-3f0b-4f18-b97f-508f51df2f3f  Build a ring farm
--   49b001cd-30a1-4062-a564-b78f646fb2fa  Evomon
--   3a0172bd-0594-414a-af6e-50fba7172f03  Gakuran
--   2570b17e-6df8-4c31-88f2-ed119f7eb51e  Redliner
--   9e061a43-d4e2-4375-bdb0-d4f371d35fe7  Strongest Battlegrounds
--   a74ef492-4241-477e-9761-526533d0ae06  Survive the Apocalypse
--
-- Live games this migration does not classify (they keep NO identity row;
-- "Robux Sell" by decision, any others simply have no reviewed decision yet):
--   ba8427f2-95bf-4a4c-b1ba-8c7709448c15  Blox Burg
--   1e6a23e2-e6a5-4d2b-a685-b33c943bcf5a  Drag Simulator
--   f67125ef-5a16-4e7d-83c0-ec375cfb1f53  Robux Sell
--
-- Safety:
--   - public.games is only read. No game row, UUID, or column changes.
--   - No DELETE, no reinsert, no fuzzy matching.
--   - Guards RAISE before any insert if migration 063 is missing, direct
--     writes would not be audited, an expected game is missing or renamed,
--     the seed repeats a game or universe, or a trusted universe is already
--     verified for a different game.
--   - Inserts use ON CONFLICT (game_id) DO NOTHING. Every seeded game is then
--     checked field by field; an existing row that differs from this seed
--     RAISEs (rolling back the whole migration) instead of being overwritten.
--   - Re-running is a no-op: no rows change and no audit entries are added.
--   - New rows are recorded by the migration 063 audit trigger with
--     write_path = 'direct_sql'.
--
-- Requires migration 063. Run in Supabase SQL Editor. Safe to run multiple times.

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Preconditions
-- -----------------------------------------------------------------------------

DO $$
BEGIN
  IF to_regclass('public.games') IS NULL THEN
    RAISE EXCEPTION 'Migration 064 requires public.games';
  END IF;

  IF to_regclass('public.game_roblox_identity') IS NULL
     OR to_regclass('public.game_roblox_identity_audit_log') IS NULL
     OR to_regprocedure('public.set_game_roblox_identity(uuid, text, bigint, bigint, text, text, bigint, text, jsonb, text, text)') IS NULL
     OR to_regprocedure('public.audit_game_roblox_identity_direct_write()') IS NULL THEN
    RAISE EXCEPTION 'Migration 064 requires migration 063 (game_roblox_identity, its audit log, and set_game_roblox_identity)';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger t
    WHERE t.tgrelid = 'public.game_roblox_identity'::regclass
      AND t.tgname = 'game_roblox_identity_audit_direct_write'
      AND t.tgenabled IN ('O', 'A')
  ) THEN
    RAISE EXCEPTION 'Migration 064 requires the enabled migration 063 audit trigger game_roblox_identity_audit_direct_write';
  END IF;

  IF current_setting('session_replication_role') <> 'origin' THEN
    RAISE EXCEPTION 'Migration 064 must run with session_replication_role = origin so its writes are audited';
  END IF;

  IF current_setting('xob.game_roblox_identity_rpc', true) = 'on' THEN
    RAISE EXCEPTION 'Migration 064 must not run with xob.game_roblox_identity_rpc = on (it suppresses direct_sql audit entries)';
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 2. Seed data (literals generated from the Store sources above)
-- -----------------------------------------------------------------------------

CREATE TEMP TABLE migration_064_seed (
  game_id               uuid        NOT NULL,
  expected_game_name    text        NOT NULL,
  status                text        NOT NULL,
  universe_id           bigint,
  root_place_id         bigint,
  verified_roblox_name  text,
  verified_creator_type text,
  verified_creator_id   bigint,
  verification_method   text,
  verified_at           timestamptz,
  review_note           text,
  verification_evidence jsonb       NOT NULL
) ON COMMIT DROP;

INSERT INTO migration_064_seed (
  game_id, expected_game_name, status,
  universe_id, root_place_id, verified_roblox_name, verified_creator_type, verified_creator_id,
  verification_method, verified_at, review_note,
  verification_evidence
) VALUES
  -- Anime Expedition
  ('f99ed2be-2074-4a0e-ae3a-409f3c8ef013', 'Anime Expedition', 'verified',
   7613921865, 84515722934860, '[🌘] Anime Expeditions', 'Group', 35929511,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Expeditions Entertainment","creator_has_verified_badge":true}}$evidence$),
  -- Anime Fighting Simulator Endless
  ('20ba81fd-54b3-4130-966e-0d2c22f8950b', 'Anime Fighting Simulator Endless', 'verified',
   9266873836, 130247632398296, 'Anime Fighting Simulator: Endless', 'Group', 361078446,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"AFS: Endless","creator_has_verified_badge":true}}$evidence$),
  -- Anime Origins
  ('6aa7180c-4199-454c-9a6a-b87c22766aab', 'Anime Origins', 'verified',
   8946565814, 129932912185311, '[UPD1 🦂] Anime Origins', 'Group', 111457579,
   'legacy_json_import', '2026-08-18T03:14:14+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"603b50dc7ec7b5176ef133b87ffd3d9e98050645","mapping_introduced_at":"2026-08-18T03:14:14+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","original_method_attested_by":"legacy_source_comment","per_game_overlap_evidence_recorded":false,"trust_basis":"No per-game overlap evidence was recorded. Commit 603b50dc7ec7b5176ef133b87ffd3d9e98050645, which added this mapping, only states that it registers Anime Origins' verified Roblox universe id. Trust comes from the legacy reviewed source: the mapping is in roblox-universe-ids.json, and roblox-universe-ids.ts states that every entry except Karinderya was confirmed by exact game pass name overlap.","legacy_comment_timing":"That roblox-universe-ids.ts statement was first written in commit e696839e5aa46d764ca8125edbfe1510d30c8bab, before this mapping was added, and was last amended in commit 8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7 while this mapping was present.","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Origins Project","creator_has_verified_badge":true}}$evidence$),
  -- Anime Squadron
  ('a75388dd-37ec-4edb-8cb3-737a4016aa72', 'Anime Squadron', 'verified',
   8356066619, 71132543521245, '[🗡️UPD 4.0🟠] Anime Squadron', 'Group', 9190691,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Komplex Studio","creator_has_verified_badge":false}}$evidence$),
  -- Anime Vanguards
  ('947ec635-2859-4984-88de-9e2594309ca2', 'Anime Vanguards', 'verified',
   5578556129, 16146832113, 'Anime Vanguards: Wrathful Assault', 'Group', 17219742,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Kitawari","creator_has_verified_badge":false}}$evidence$),
  -- Anime Warriors III
  ('53a640b1-c16a-4912-8d4e-8a5558ab5b22', 'Anime Warriors III', 'verified',
   6409513651, 18923620224, '[🗼 UPDATE 5.0] Anime Warriors III', 'Group', 34783288,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Arc I: Warriors","creator_has_verified_badge":true}}$evidence$),
  -- Blox Fruits
  ('155d2360-c956-4982-9965-9a0b303d749e', 'Blox Fruits', 'verified',
   994732206, 2753915549, '[🧲] Blox Fruits', 'Group', 4372130,
   'legacy_json_import', '2026-08-08T01:59:50+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"9f93a979e618d487e908cf2f61336f7efd386399","mapping_introduced_at":"2026-08-08T01:59:50+08:00","original_method":"manual_content_icon_match","original_method_basis":"commit 9f93a979e618d487e908cf2f61336f7efd386399: identity established before the mapping was added from exact fruit-name matches in the game's own description (40/41), a matching genre, and a game icon byte-identical to store_games.icon_url. Not established by game pass overlap.","original_evidence":{"source":"commit 9f93a979e618d487e908cf2f61336f7efd386399","description_fruit_name_overlap":"40/41","genre_match":true,"game_icon_byte_identical_to_store_icon":true},"later_gamepass_overlap_count":5,"later_gamepass_overlap_names":["Dark Blade","Fruit Notifier","2x Mastery","2x Money","Fast Boats"],"later_gamepass_overlap_note":"Exact Game Pass name matches found when scripts/sync-roblox-gamepasses.mjs ran after the mapping was added. Supporting evidence only, not the original basis.","legacy_comment_note":"The roblox-universe-ids.ts statement that entries were confirmed by game pass overlap was first written in commit e696839e5aa46d764ca8125edbfe1510d30c8bab, before this mapping was added, and does not describe how this mapping was established.","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Gamer Robot Inc","creator_has_verified_badge":true}}$evidence$),
  -- Bloxburg
  ('21261c9b-8604-45e4-9eaa-9fd50f4b3a89', 'Bloxburg', 'verified',
   88070565, 185655149, '[🍽] Welcome to Bloxburg', 'Group', 8505490,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Bloxburg Development","creator_has_verified_badge":true}}$evidence$),
  -- Brookhaven
  ('ab507856-aafc-4b3c-9122-99c9b1102f02', 'Brookhaven', 'verified',
   1686885941, 4924922222, 'Brookhaven 🏡RP', 'Group', 3104358,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Brookhaven by Voldex","creator_has_verified_badge":false}}$evidence$),
  -- Catch and Tame
  ('c40a8209-60ac-4f73-8977-c1f4ad27c8ad', 'Catch and Tame', 'verified',
   9091133975, 96645548064314, '[🌪️] Catch And Tame!', 'Group', 4127076,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Manta Games","creator_has_verified_badge":false}}$evidence$),
  -- CDID
  ('92c69098-2311-484d-9e73-40c83c46c0ad', 'CDID', 'verified',
   2640407187, 6911148748, '(UPDATE!) Car Driving Indonesia', 'Group', 10884667,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"CDID Studio Official Group","creator_has_verified_badge":true}}$evidence$),
  -- Diesel n Steel
  ('a535c200-d1c8-473a-9090-75adc656103d', 'Diesel n Steel', 'verified',
   6466802953, 131667667758514, '🚍Diesel n'' Steel', 'Group', 278415846,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Diesel n' Steel Official Group","creator_has_verified_badge":true}}$evidence$),
  -- Drag Drive Simulator
  ('ca3463cd-4033-4505-b6a8-441d450df10a', 'Drag Drive Simulator', 'verified',
   7089588429, 131378148336503, '(EVENT x LIMITED UPDATE 🇮🇩) Drag Drive Simulator', 'Group', 11378976,
   'legacy_json_import', '2026-08-06T13:08:15+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"4b542ab689cfa4d5c9c3e533b6ea8b61c25b9eb4","mapping_introduced_at":"2026-08-06T13:08:15+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"ADV Gamers Team","creator_has_verified_badge":true}}$evidence$),
  -- EVADE
  ('89ef8e89-6293-4e16-9b08-048ce03e191f', 'EVADE', 'verified',
   3647333358, 9872472334, 'Evade', 'Group', 5693735,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Hexagon Development Community","creator_has_verified_badge":true}}$evidence$),
  -- Grow a garden 2
  ('ec7b0020-d616-485b-a151-f5fc2d541c9b', 'Grow a garden 2', 'verified',
   10200395747, 97598239454123, 'Grow a Garden 2', 'Group', 432538536,
   'legacy_json_import', '2026-08-06T13:08:15+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"4b542ab689cfa4d5c9c3e533b6ea8b61c25b9eb4","mapping_introduced_at":"2026-08-06T13:08:15+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","recorded_evidence":[{"source":"src/config/roblox-universe-ids.ts","note":"Pilot entry. The top Roblox search result for Grow a Garden is a different, nearly-empty universe; this universe was confirmed by cross-referencing real product names (Grappling Hook, Power Hose, Vine Wrapper) against the candidate universes' game pass lists."}],"roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Strawberreh Squad","creator_has_verified_badge":true}}$evidence$),
  -- Hypershot
  ('e441b38e-ffc4-437a-915f-c43127f713a3', 'Hypershot', 'verified',
   5995470825, 17516596118, '🔥Hypershot', 'Group', 3385385,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Frosted Studio","creator_has_verified_badge":true}}$evidence$),
  -- Iron Soul Dungeon
  ('112fe976-ef3c-4883-bb69-9adf255dac54', 'Iron Soul Dungeon', 'verified',
   9910245722, 117533937949084, 'Iron Soul: Dungeon', 'Group', 559846885,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Iron Soul","creator_has_verified_badge":true}}$evidence$),
  -- Karinderya
  ('84372024-ee1c-43a0-bbfb-6227c43039d3', 'Karinderya', 'verified',
   10648820673, 116497287371701, '[🔥] Karinderya!', 'Group', 985559810,
   'legacy_json_import', '2026-09-15T18:27:54+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","mapping_introduced_at":"2026-09-15T18:27:54+08:00","original_method":"owner_confirmed","original_method_basis":"roblox-universe-ids.ts: universe and root place ids confirmed directly by the store owner rather than by product-list cross-reference","owner_confirmed_root_place_id":116497287371701,"roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"SILOG","creator_has_verified_badge":true}}$evidence$),
  -- Keyboard Escape | Candy & Chocolate
  ('6d14e786-0981-42e2-a099-9eaacc9574b3', 'Keyboard Escape | Candy & Chocolate', 'verified',
   9584852943, 95082159892680, '+1 Speed Keyboard Escape | Candy & Chocolate', 'Group', 1074557114,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"SecretVerse Studio","creator_has_verified_badge":true}}$evidence$),
  -- KICK A LUCKY BLOCK
  ('2ab0f0de-d241-48a0-a9b5-e4e6e2deaea8', 'KICK A LUCKY BLOCK', 'verified',
   10004244222, 89469502395769, 'Kick a Lucky Block', 'Group', 1041977165,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"No More Flops","creator_has_verified_badge":true}}$evidence$),
  -- Midnight chasers
  ('92ae57c5-a41b-4bc6-91c5-e651b123ab55', 'Midnight chasers', 'verified',
   4793836769, 13822562292, '[🙌HANDS]🚗Midnight Chasers: Highway Racing', 'Group', 16528477,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Midnight In-dev","creator_has_verified_badge":false}}$evidence$),
  -- re:rangers X
  ('22478396-a353-4f5e-a214-c8c2c0ddaf57', 're:rangers X', 'verified',
   9774981774, 111446873000464, '[🏖️ PT2 SUMMER] Re:Rangers X', 'Group', 15009415,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"[B:S] ARX Team","creator_has_verified_badge":false}}$evidence$),
  -- Run a Restaurant
  ('ea7fa41c-e8f8-4dc6-96b2-85494b90ce16', 'Run a Restaurant', 'verified',
   9970645639, 77843161404023, 'Run a Restaurant!', 'Group', 75550158,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Burnt Toast Labs!","creator_has_verified_badge":true}}$evidence$),
  -- Slime RNG
  ('3304b0e6-cbdd-4ddd-8232-d994a7d515cb', 'Slime RNG', 'verified',
   9792947201, 92416421522960, 'Slime RNG', 'Group', 15794692,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","recorded_evidence":[{"source":"commit e696839e5aa46d764ca8125edbfe1510d30c8bab","note":"Full-catalog rollout: 7/7 exact game pass name overlap."}],"roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Stouts Studio","creator_has_verified_badge":true}}$evidence$),
  -- Storage Hunters
  ('89ff760e-bdb1-43a9-9a0d-d6bf1e6dd0c9', 'Storage Hunters', 'verified',
   10261267004, 98800969324557, '[🌵UPD] Storage Hunters: Open World', 'Group', 9640154,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Absolute Zero!","creator_has_verified_badge":true}}$evidence$),
  -- Wizard Alchemy
  ('0de6d80e-b843-4e99-8d83-2c1a9befd232', 'Wizard Alchemy', 'verified',
   10006104044, 118821269826806, 'Wizard Alchemy[🕸Spider Lair UPD]', 'Group', 509055872,
   'legacy_json_import', '2026-08-06T13:35:23+08:00', NULL,
   $evidence${"source":"roblox-universe-ids.json","source_path":"src/config/roblox-universe-ids.json","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_last_changed_commit":"8ffb57c0d905fd0a14474961ab2f4bfd4954d1d7","source_json_blob":"6f0471232ba1bea946fda69c708b1c79972b4dd1","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","mapping_introduced_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","mapping_introduced_at":"2026-08-06T13:35:23+08:00","original_method":"gamepass_overlap","original_method_basis":"roblox-universe-ids.ts: confirmed with at least 2-3 (usually 5+) exact product-name overlaps against the live Roblox game pass list, never on name similarity alone","roblox_api_snapshot":{"endpoint":"https://games.roblox.com/v1/games","fetched_at":"2026-09-15T12:39:11.496Z","creator_name":"Muggle Academy","creator_has_verified_badge":true}}$evidence$),
  -- ROBUX PLUS
  ('cc1ec858-663c-4ff2-9185-e3d587780b46', 'ROBUX PLUS', 'not_roblox',
   NULL, NULL, NULL, NULL, NULL,
   NULL, NULL, 'Robux currency product sold through the Store, not a Roblox experience.',
   $evidence${"source":"roblox_identity_rollout_plan","decision":"not_roblox","basis":"Robux currency pseudo-game approved as not_roblox in the Phase 2 identity import plan","store_reference":"src/config/robux-products.ts","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c"}$evidence$),
  -- Robux Sell — Covered Tax
  ('bf10c2e9-d9f2-4f86-8c7d-5c94b7354a75', 'Robux Sell — Covered Tax', 'not_roblox',
   NULL, NULL, NULL, NULL, NULL,
   NULL, NULL, 'Robux currency product sold through the Store, not a Roblox experience.',
   $evidence${"source":"roblox_identity_rollout_plan","decision":"not_roblox","basis":"Robux currency pseudo-game approved as not_roblox in the Phase 2 identity import plan","store_reference":"src/config/robux-via-link.ts","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c"}$evidence$),
  -- Robux Sell — No Tax
  ('e5318653-6b19-417c-9f89-1a7baa2331aa', 'Robux Sell — No Tax', 'not_roblox',
   NULL, NULL, NULL, NULL, NULL,
   NULL, NULL, 'Robux currency product sold through the Store, not a Roblox experience.',
   $evidence${"source":"roblox_identity_rollout_plan","decision":"not_roblox","basis":"Robux currency pseudo-game approved as not_roblox in the Phase 2 identity import plan","store_reference":"src/config/robux-via-link.ts","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c"}$evidence$),
  -- Build a ring farm
  ('c1855e24-3f0b-4f18-b97f-508f51df2f3f', 'Build a ring farm', 'needs_review',
   NULL, NULL, NULL, NULL, NULL,
   NULL, NULL, 'Deliberately not configured in roblox-universe-ids.ts (needs manual follow-up, do not guess): the one found candidate universe currently has zero Game Passes to check against (all its products are likely Developer Products already).',
   $evidence${"source":"roblox-universe-ids.ts","source_path":"src/config/roblox-universe-ids.ts","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","documented_in_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","decision":"deliberately_not_configured","documented_reason":"the one found candidate universe currently has zero Game Passes to check against (all its products are likely Developer Products already).","candidate_universe_ids_recorded":false}$evidence$),
  -- Evomon
  ('49b001cd-30a1-4062-a564-b78f646fb2fa', 'Evomon', 'needs_review',
   NULL, NULL, NULL, NULL, NULL,
   NULL, NULL, 'Deliberately not configured in roblox-universe-ids.ts (needs manual follow-up, do not guess): only "VIP" overlapped, too generic/common a name across unrelated games to trust alone.',
   $evidence${"source":"roblox-universe-ids.ts","source_path":"src/config/roblox-universe-ids.ts","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","documented_in_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","decision":"deliberately_not_configured","documented_reason":"only \"VIP\" overlapped, too generic/common a name across unrelated games to trust alone.","candidate_universe_ids_recorded":false}$evidence$),
  -- Gakuran
  ('3a0172bd-0594-414a-af6e-50fba7172f03', 'Gakuran', 'needs_review',
   NULL, NULL, NULL, NULL, NULL,
   NULL, NULL, 'Deliberately not configured in roblox-universe-ids.ts (needs manual follow-up, do not guess): zero overlap found.',
   $evidence${"source":"roblox-universe-ids.ts","source_path":"src/config/roblox-universe-ids.ts","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","documented_in_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","decision":"deliberately_not_configured","documented_reason":"zero overlap found.","candidate_universe_ids_recorded":false}$evidence$),
  -- Redliner
  ('2570b17e-6df8-4c31-88f2-ed119f7eb51e', 'Redliner', 'needs_review',
   NULL, NULL, NULL, NULL, NULL,
   NULL, NULL, 'Deliberately not configured in roblox-universe-ids.ts (needs manual follow-up, do not guess): candidate universe has zero Game Passes to check against.',
   $evidence${"source":"roblox-universe-ids.ts","source_path":"src/config/roblox-universe-ids.ts","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","documented_in_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","decision":"deliberately_not_configured","documented_reason":"candidate universe has zero Game Passes to check against.","candidate_universe_ids_recorded":false}$evidence$),
  -- Strongest Battlegrounds
  ('9e061a43-d4e2-4375-bdb0-d4f371d35fe7', 'Strongest Battlegrounds', 'needs_review',
   NULL, NULL, NULL, NULL, NULL,
   NULL, NULL, 'Deliberately not configured in roblox-universe-ids.ts (needs manual follow-up, do not guess): TWO live, similarly-named candidate universes each partially matched our products (5/8 and 3/5 overlaps) — genuinely ambiguous which is ours, so neither was added.',
   $evidence${"source":"roblox-universe-ids.ts","source_path":"src/config/roblox-universe-ids.ts","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","documented_in_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","decision":"deliberately_not_configured","documented_reason":"TWO live, similarly-named candidate universes each partially matched our products (5/8 and 3/5 overlaps) — genuinely ambiguous which is ours, so neither was added.","candidate_universe_ids_recorded":false}$evidence$),
  -- Survive the Apocalypse
  ('a74ef492-4241-477e-9761-526533d0ae06', 'Survive the Apocalypse', 'needs_review',
   NULL, NULL, NULL, NULL, NULL,
   NULL, NULL, 'Deliberately not configured in roblox-universe-ids.ts (needs manual follow-up, do not guess): the found candidate universe has zero Game Passes to check against.',
   $evidence${"source":"roblox-universe-ids.ts","source_path":"src/config/roblox-universe-ids.ts","source_repository":"BudgetWise_Store","source_commit":"e81f2515b08740722ad7bef82eb6b9debb9f867c","source_ts_blob":"8f3ddb270054f50f734c21756b7797f7624506d2","documented_in_commit":"e696839e5aa46d764ca8125edbfe1510d30c8bab","decision":"deliberately_not_configured","documented_reason":"the found candidate universe has zero Game Passes to check against.","candidate_universe_ids_recorded":false}$evidence$);

-- -----------------------------------------------------------------------------
-- 3. Guards (before any identity write)
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  v_list text;
BEGIN
  SELECT string_agg(format('%s=%s', status, n), ', ' ORDER BY status)
  INTO v_list
  FROM (SELECT status, count(*) AS n FROM migration_064_seed GROUP BY status) c;

  IF (SELECT count(*) FROM migration_064_seed) <> 35
     OR (SELECT count(*) FROM migration_064_seed WHERE status = 'verified') <> 26
     OR (SELECT count(*) FROM migration_064_seed WHERE status = 'not_roblox') <> 3
     OR (SELECT count(*) FROM migration_064_seed WHERE status = 'needs_review') <> 6 THEN
    RAISE EXCEPTION 'Migration 064 seed has unexpected counts: %', v_list;
  END IF;

  SELECT string_agg(game_id::text, ', ')
  INTO v_list
  FROM (SELECT game_id FROM migration_064_seed GROUP BY game_id HAVING count(*) > 1) d;

  IF v_list IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 064 seed repeats game ids: %', v_list;
  END IF;

  SELECT string_agg(universe_id::text, ', ')
  INTO v_list
  FROM (
    SELECT universe_id FROM migration_064_seed
    WHERE status = 'verified'
    GROUP BY universe_id HAVING count(*) > 1
  ) d;

  IF v_list IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 064 seed repeats trusted universe ids: %', v_list;
  END IF;

  IF EXISTS (SELECT 1 FROM migration_064_seed WHERE game_id = 'f67125ef-5a16-4e7d-83c0-ec375cfb1f53') THEN
    RAISE EXCEPTION 'Migration 064 must leave the hidden legacy Robux Sell game (f67125ef-5a16-4e7d-83c0-ec375cfb1f53) unclassified';
  END IF;

  SELECT string_agg(format('%s (%s)', s.game_id, s.expected_game_name), ', ' ORDER BY s.expected_game_name)
  INTO v_list
  FROM migration_064_seed s
  WHERE NOT EXISTS (SELECT 1 FROM public.games g WHERE g.id = s.game_id);

  IF v_list IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 064 expected games are missing from public.games: %', v_list;
  END IF;

  SELECT string_agg(format('%s expected %L, found %L', s.game_id, s.expected_game_name, g.name), '; ' ORDER BY s.expected_game_name)
  INTO v_list
  FROM migration_064_seed s
  JOIN public.games g ON g.id = s.game_id
  WHERE g.name IS DISTINCT FROM s.expected_game_name;

  IF v_list IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 064 game_id/name pairings no longer match: %', v_list;
  END IF;

  SELECT string_agg(format('universe %s is verified for game %s, seed expects game %s', i.universe_id, i.game_id, s.game_id), '; ')
  INTO v_list
  FROM public.game_roblox_identity i
  JOIN migration_064_seed s
    ON s.status = 'verified'
   AND s.universe_id = i.universe_id
  WHERE i.status = 'verified'
    AND i.game_id <> s.game_id;

  IF v_list IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 064 trusted universe ids are already verified for other games: %', v_list;
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 4. Insert missing rows only (existing rows are never overwritten)
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  v_inserted integer;
BEGIN
  INSERT INTO public.game_roblox_identity (
    game_id, status, universe_id, root_place_id, verified_roblox_name,
    verified_creator_type, verified_creator_id, verification_method,
    verification_evidence, verified_at, review_note
  )
  SELECT
    game_id, status, universe_id, root_place_id, verified_roblox_name,
    verified_creator_type, verified_creator_id, verification_method,
    verification_evidence, verified_at, review_note
  FROM migration_064_seed
  ORDER BY game_id
  ON CONFLICT (game_id) DO NOTHING;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  RAISE NOTICE 'Migration 064 inserted % of 35 seed rows', v_inserted;
END $$;

-- -----------------------------------------------------------------------------
-- 5. Every seeded game must now hold exactly the seed identity
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  v_list         text;
  v_verified     bigint;
  v_not_roblox   bigint;
  v_needs_review bigint;
BEGIN
  SELECT string_agg(
           format('%s (%s): %s', s.game_id, s.expected_game_name,
             CASE
               WHEN i.game_id IS NULL THEN 'identity row missing'
               ELSE array_to_string(ARRAY[
                 CASE WHEN i.status IS DISTINCT FROM s.status THEN 'status' END,
                 CASE WHEN i.universe_id IS DISTINCT FROM s.universe_id THEN 'universe_id' END,
                 CASE WHEN i.root_place_id IS DISTINCT FROM s.root_place_id THEN 'root_place_id' END,
                 CASE WHEN i.verified_roblox_name IS DISTINCT FROM s.verified_roblox_name THEN 'verified_roblox_name' END,
                 CASE WHEN i.verified_creator_type IS DISTINCT FROM s.verified_creator_type THEN 'verified_creator_type' END,
                 CASE WHEN i.verified_creator_id IS DISTINCT FROM s.verified_creator_id THEN 'verified_creator_id' END,
                 CASE WHEN i.verification_method IS DISTINCT FROM s.verification_method THEN 'verification_method' END,
                 CASE WHEN i.verification_evidence IS DISTINCT FROM s.verification_evidence THEN 'verification_evidence' END,
                 CASE WHEN i.verified_at IS DISTINCT FROM s.verified_at THEN 'verified_at' END,
                 CASE WHEN i.verified_by IS NOT NULL THEN 'verified_by' END,
                 CASE WHEN i.review_note IS DISTINCT FROM s.review_note THEN 'review_note' END
               ], ', ')
             END),
           '; ' ORDER BY s.expected_game_name)
  INTO v_list
  FROM migration_064_seed s
  LEFT JOIN public.game_roblox_identity i ON i.game_id = s.game_id
  WHERE i.game_id IS NULL
     OR i.verified_by IS NOT NULL
     OR (i.status, i.universe_id, i.root_place_id, i.verified_roblox_name,
         i.verified_creator_type, i.verified_creator_id, i.verification_method,
         i.verification_evidence, i.verified_at, i.review_note)
        IS DISTINCT FROM
        (s.status, s.universe_id, s.root_place_id, s.verified_roblox_name,
         s.verified_creator_type, s.verified_creator_id, s.verification_method,
         s.verification_evidence, s.verified_at, s.review_note);

  IF v_list IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 064 found existing Roblox identities that conflict with the reviewed seed (nothing was changed): %', v_list;
  END IF;

  SELECT count(*) FILTER (WHERE i.status = 'verified'),
         count(*) FILTER (WHERE i.status = 'not_roblox'),
         count(*) FILTER (WHERE i.status = 'needs_review')
  INTO v_verified, v_not_roblox, v_needs_review
  FROM public.game_roblox_identity i
  JOIN migration_064_seed s ON s.game_id = i.game_id;

  IF v_verified <> 26 OR v_not_roblox <> 3 OR v_needs_review <> 6 THEN
    RAISE EXCEPTION 'Migration 064 final counts are verified %, not_roblox %, needs_review % (expected 26, 3, 6)',
      v_verified, v_not_roblox, v_needs_review;
  END IF;

  RAISE NOTICE 'Migration 064 identities: verified %, not_roblox %, needs_review %', v_verified, v_not_roblox, v_needs_review;
END $$;

COMMIT;
